#pragma once

// Developer Options
#define DEBUG_ENABLED 1

// 抗锯齿
#define MSAA_SAMPLE_AMOUNT 4

// 窗口设置
#define WINDOW_X_RESOLUTION 1600
#define WINDOW_Y_RESOLUTION 900
#define V_SYNC 0
#define FULLSCREEN_MODE 0 

// 纹理过滤方式设置
#define ANISOTROPIC_FILTERING_LEVEL 8.0f

//IBL 设置
#define LIGHT_PROBE_RESOLUTION 32
#define REFLECTION_PROBE_MIP_COUNT 5
#define REFLECTION_PROBE_RESOLUTION 128
#define IBL_CAPTURE_RESOLUTION 256
#define BRDF_LUT_RESOLUTION 512

#define NEAR_PLANE 0.1f
#define FAR_PLANE 1000.0f

// 阴影设置
#define SHADOWMAP_RESOLUTION_X 2048
#define SHADOWMAP_RESOLUTION_Y 2048
#define SHADOWMAP_NEAR_PLANE 1.0f
#define SHADOWMAP_FAR_PLANE 400.0f

// 是否前向渲染
#define FORWARD_RENDER 0
